plugin-prefix: "&7[&aPixel&fGenerator&7] &8"

generators-interactions:
    can-break: false
    can-explode: false
    can-move-by-pistons: false
    can-burn: false
    can-lava-destroy: false
    can-entities-move: false

gui:
    window:
        name: Generator GUI
    items:
        interval-item:
            item: CLOCK
            name: Interval
        quantity-item:
            item: GLOWSTONE_DUST
            name: Quantity