plugin-prefix: "&7[&bPixel&fGenerator&7] &8"

generators-interactions:
    can-break: false
    can-explode: false
    can-move-by-pistons: false
    can-burn: false
    can-lava-destroy: false
    can-entities-move: false

gui:
    window:
        name: Generator GUI
    items:
        interval-item:
            item: CLOCK
            name: Interval
        quantity-item:
            item: GLOWSTONE_DUST
            name: Quantity

custom-items:
    - item1:
        name: Custom item example
        lore-lines:
            - lore line 1
            - lore line 2
            - lone line 3
        material: DIAMOND