# Configurazione del plugin PixelGenerator
plugin-prefix: "&7[&aPixel&fGenerator&7] &8"

# Messaggi configurabili
generators-interactions:
    can-break: false
    can-explode: false
    can-move-by-pistons: false
    can-burn: false
    can-lava-destroy: false
    can-entities-move: false