name: PixelGenerator
version: '1.0-SNAPSHOT'
main: me.giacomo.minecraft.pixelGenerator.PixelGenerator
api-version: '1.21'
depend:
  - DecentHolograms
commands:
  generator:
      description: Create and manage item generators
      usage: /generator <blockName> <itemName> <interval> <quantity>
      permission: pixelgenerator.command.generator
permissions:
  pixelgenerator.place:
    description: Allow placing generator blocks.
    default: true
  pixelgenerator.break:
    description: Allow destroying generator blocks.
    default: true
  pixelgenerator.interact:
    description: Allow interacting with generator blocks.
    default: false
  pixelgenerator.admin.create:
    description: Allows creating generators.
    default: false
  pixelgenerator.admin.list:
    description: Allows listing generators.
    default: false
  pixelgenerator.admin.debug:
    description: Allows enabling debug mode.
    default: false
  pixelgenerator.admin.*:
    description: Grants access to all admin commands.
    default: op
