name: PixelGenerator
version: '1.0-SNAPSHOT'
main: me.giacomo.minecraft.pixelGenerator.PixelGenerator
api-version: '1.21'
commands:
  generator:
      description: Create and manage item generators
      usage: /generator <blockName> <itemName> <interval> <quantity>
      permission: pixelgenerator.command.generator
permissions:
  pixelgenerator.use:
    description: Allows using generator commands.
    default: true
  pixelgenerator.create:
    description: Allows creating generators.
    default: true
  pixelgenerator.list:
    description: Allows listing generators.
    default: true
  pixelgenerator.remove:
    description: Allows removing generators.
    default: true
  pixelgenerator.admin.*:
    description: Grants access to all admin commands.
    default: op
